trigger: 
- main


pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: 'amgenpoc'
  dockerfilePath: 'Dockerfile'
  #Add date timesamp in build tag
  #tag: '$(Build.BuildId)'
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'amgenPOC-acr-connection'
stages:
#Runs the tests using pytest. It installs the dependencies and then runs the tests in the tests/ directory.
- stage: Test
  displayName: Run Tests
  jobs:
  - job: PyTest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
      displayName: 'Use Python 3.11'

    # Install dependencies and run tests using pytest
    - script: pip install -r requirements.txt pytest
      displayName: 'Install dependencies'

      # Run pytest with verbose output and short traceback - what is short traceback? Short traceback is a pytest option that limits the amount of traceback information shown when a test fails. It provides a concise summary of the failure, making it easier to identify the issue without overwhelming the user with too much information. This can be particularly useful in CI/CD pipelines where you want to quickly understand test failures without sifting through extensive logs.
    - script: python -m pytest tests/ -v --tb=short
      displayName: 'Run pytest'

# If the tests pass, this stage builds a Docker image using the specified Dockerfile and tags it with the build ID and 'latest'. It uses the Docker task to perform the build.
- stage: Build
  displayName: Build Docker Image
  dependsOn: Test
  # The condition 'succeeded()' ensures that this stage only runs if the previous stage (Test) was successful. If the tests fail, the pipeline will stop and the Build stage will not execute.
  condition: succeeded()
  jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: 'Build image'
      inputs:
        command: build
        containerRegistry: '$(dockerRegistryServiceConnection)'
        dockerfile: $(dockerfilePath)
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest
# If the build is successful and the source branch is 'main', this stage pushes the Docker image to a container registry. It uses the Docker task to perform the push, and it checks that the build succeeded and that the source branch is 'main' before executing.
- stage: Push
  displayName: Push to Registry
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: DockerPush
    steps:
    - task: Docker@2
      displayName: 'Push image'
      inputs:
        command: push
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest
